/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ConversationId = IDL.Nat;
export const MessageId = IDL.Nat;
export const UserId = IDL.Principal;
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : MessageId,
  'text' : IDL.Text,
  'author' : UserId,
  'conversationId' : ConversationId,
  'timestamp' : Time,
});
export const Preview = IDL.Record({
  'lastActivity' : Time,
  'lastMessage' : IDL.Text,
  'conversationId' : ConversationId,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationMessages' : IDL.Func(
      [ConversationId],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getConversations' : IDL.Func([], [IDL.Vec(Preview)], ['query']),
  'getOrCreateConversation' : IDL.Func([UserId], [ConversationId], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserType' : IDL.Func([], [IDL.Principal], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([ConversationId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ConversationId = IDL.Nat;
  const MessageId = IDL.Nat;
  const UserId = IDL.Principal;
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : MessageId,
    'text' : IDL.Text,
    'author' : UserId,
    'conversationId' : ConversationId,
    'timestamp' : Time,
  });
  const Preview = IDL.Record({
    'lastActivity' : Time,
    'lastMessage' : IDL.Text,
    'conversationId' : ConversationId,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationMessages' : IDL.Func(
        [ConversationId],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getConversations' : IDL.Func([], [IDL.Vec(Preview)], ['query']),
    'getOrCreateConversation' : IDL.Func([UserId], [ConversationId], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserType' : IDL.Func([], [IDL.Principal], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([ConversationId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };